### ISSUE TITLE
Store game results in localStorage

### ISSUE THREAD

**Issue by epicalex** [epicalex/basic-ulti-stats#2]
To add some persistence, let's knock together saving the stats out into localSotrage.

It should be possible to save multiple games into Storage, so each game will need a UUID.

**Comment by stevewalton28** [comment]
What do we want to do with it once it's stored? Just be able to view within the browser?

**Comment by epicalex** [comment]
Yeah, idea was just to be able to go back to individual games from the listing and see the stats.

I've got all of the right hand table set to store the data, but just noticed that it does point by point on the left, so working out how to be able to store and retrieve that.

To retrieve the data, I'm just going to pass a query string with the game's UUID and then get the other items off the back of that.

Not super pretty but it will work and I don't have to think too much to just get it done

**Comment by epicalex** [comment]
Resolved in #4
